force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent__c/fields/Child_Number__c.field-meta.xml
<CustomField>
    <fullName>Child_Number__c</fullName>
    <label>Child Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report_Card__c/Report_Card__c.object-meta.xml
<CustomObject>
    <label>Report Card</label>
    <nameField>
        <displayFormat>RC-{000}</displayFormat>
        <label>Report Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Card__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Report Cards</relationshipLabel>
    <relationshipName>Report_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StudentTriggerHandler.cls
public class StudentTriggerHandler {
    public static void reportCardCreation(List<Student__c> stdList){
        List<Report_Card__c> rcList = new List<Report_Card__c>();
        for(Student__c std:stdList){
            Report_Card__c rc = new Report_Card__c();
            rc.Student__c = std.Id;
            rcList.add(rc);
        }
        insert rcList;
    }
    
    
    
    
    public static void activeChildNumber(List<Student__c> studentList){
       List<Parent__c> parentList = new List<Parent__c>();
      
        Set<Id> ParentId = new Set<Id>();
        for(Student__c st:studentList){
            ParentId.add(st.Parent__c);
        }
        
        for(Parent__c p:[SELECT Id, Name, Child_Number__c, (SELECT Id FROM Students__r WHERE isActive__c=true) FROM Parent__c WHERE id IN:ParentId ]){
            
            p.Child_Number__c = p.students__r.size();
            parentList.add(p);
        }  
        Update parentList;
    }
    
}