force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StudentTest.cls
@isTest
public class StudentTest {

    
    @testSetup static void setup(){
     Parent__c p = new Parent__c(Name='TestParent');
        insert p;
        
        
        List<Student__c> stList = new List<Student__c>();
        for(integer i=0; i<200; i++){
            Student__c st = new Student__c();
            st.Name = 'Test'+i;
			st.isActive__c = true;
            st.Parent__c = p.Id;
            
            stList.add(st);
        }
        insert stList;
    }     
@isTest
    static void reportCard(){
       test.startTest();
       
        test.stopTest();
        
        
    }

    @isTest
    static void deletion(){
      List<Student__c>  SList = [SELECT Id FROM Student__c];
        test.startTest();
        delete SList ;
        test.stopTest();
    }
}