force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent__c/fields/ReportCardUpdateTime__c.field-meta.xml
<CustomField>
    <fullName>ReportCardUpdateTime__c</fullName>
    <label>ReportCardUpdateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Report_Card__c/Report_Card__c.object-meta.xml
<CustomObject>
    <label>Report Card</label>
    <nameField>
        <displayFormat>RC-{000}</displayFormat>
        <label>Report Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Card__c/fields/Maths__c.field-meta.xml
<CustomField>
    <fullName>Maths__c</fullName>
    <label>Math</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report_Card__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Report Cards</relationshipLabel>
    <relationshipName>Report_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/rcT102Handler.cls
public class rcT102Handler {
    public static void rcDateUpdate(List<Report_Card__c> rcNewList,List<Report_Card__c> rcOldList, Map<Id, Report_Card__c> rcNewMap, Map<Id, Report_Card__c> rcOldMap ){
     /*   
        Map<Id, Parent__c> pMap = new Map<Id, Parent__c>([SELECT Id, 
																	(SELECT Id FROM Students__r WHERE id IN 
                                                         						(SELECT Report_Card__c.Student__c FROM Report_Card__c 
                                                                                 		WHERE id IN:rcNewList)) 
                                                          			FROM Parent__c ]);
        
   
        for(Parent__c p: pMap.values() ){
            p.ReportCardUpdateTime__c = system.now();
        }
        update pMap.values();
        
    }*/
    
     Map<Id, Student__c> stMap = new Map<Id, Student__c>([SELECT Id, Name, Parent__c, Parent__r.ReportCardUpdateTime__c, 
                                                      (SELECT id, Maths__c FROM Report_Cards__r) FROM Student__c WHERE Id IN 
                                                         (SELECT Student__c FROM Report_Card__c WHERE Id In:Trigger.New)]);
     
     List<Student__c> stList = new List<Student__c>();
     for(Student__c st:stMap.values() ){  
         st.parent__r.ReportCardUpdateTime__c = system.now();
         stList.add(st);     
     }
     update stList;
    }
}