force-app/main/default/objects/Report_Card__c/Report_Card__c.object-meta.xml
<CustomObject>
    <label>Report Card</label>
    <nameField>
        <displayFormat>RC-{000}</displayFormat>
        <label>Report Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Card__c/fields/Average__c.field-meta.xml
<CustomField>
    <fullName>Average__c</fullName>
    <formula>( Maths__c + English__c + Geography__c + History__c )/4</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report_Card__c/fields/English__c.field-meta.xml
<CustomField>
    <fullName>English__c</fullName>
    <label>English</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report_Card__c/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <label>Geography</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report_Card__c/fields/History__c.field-meta.xml
<CustomField>
    <fullName>History__c</fullName>
    <label>History</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report_Card__c/fields/Maths__c.field-meta.xml
<CustomField>
    <fullName>Maths__c</fullName>
    <label>Math</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report_Card__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Excellent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Report_Card_Trigger_Handler.cls
public class Report_Card_Trigger_Handler {
    public static void overallScore(List<Report_Card__c> rcList){
        for(report_card__c rc:rcList){
            if(rc.Maths__c>=0 && rc.Maths__c<=100 && rc.English__c>=0 && rc.English__c<=100 && rc.History__c>=0 && rc.History__c<=100 && rc.Geography__c>=0 && rc.Geography__c<=100){
                if(rc.average__c < 40 || rc.English__c<40 || rc.Maths__c<40) {
                    rc.Overall_Score__c = 'Fail';
                }else if(rc.Average__c<60){
                    rc.Overall_Score__c = 'Pass';
                }else if(rc.Average__c<80){
                    rc.Overall_Score__c = 'Good';
                }else{
                    rc.Overall_Score__c = 'Excellent';
                }    
            }else{
                rc.adderror('enter a valid mark!');
            }
            
        }
    }
}